services:
  db:
    image: postgres:18-alpine
    container_name: engram-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: 'engram'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

    ports:
      - '5432:5432'

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/database/scripts/:/docker-entrypoint-initdb.d/:ro

    networks:
      - engram_api_net

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d $POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  engram_api_net:
